-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["char"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -128, -56.5  ,  -128.5, -58  ,  -128.5, -63  ,  -125, -62.5  ,  -123, -60.5  ,  -122.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -130, -78.5  ,  -130.5, -83  ,  -129, -82.5  ,  -128.5, -79  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -130.5, -39  ,  -130.5, -37  ,  -132.5, -35  ,  -146, -34.5  ,  -148.5, -38  ,  -148.5, -44  ,  -136.5, -43  ,  -133, -42.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -131, -86.5  ,  -130, -78.5  ,  -132.5, -71  ,  -157, -92.5  ,  -155, -94.5  ,  -139, -94.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -138, -56.5  ,  -179, -84.5  ,  -132.5, -71  ,  -132.5, -67  ,  -134, -58.5  ,  -134.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -154, -42.5  ,  -162.5, -44  ,  -164.5, -50  ,  -150, -44.5  ,  -150.5, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -180, -58.5  ,  -180.5, -84  ,  -179, -84.5  ,  -138, -56.5  ,  -138.5, -55  ,  -168, -52.5  ,  -174, -52.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, -47  ,  -136, -46.5  ,  -148.5, -44  ,  -150, -44.5  ,  -164.5, -50  ,  -168, -52.5  ,  -138.5, -55  ,  -134.5, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -162.5, -44  ,  -154, -42.5  ,  -152.5, -35  ,  -154.5, -33  ,  -164, -32.5  ,  -166.5, -36  ,  -166.5, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -148.5, -44  ,  -136, -46.5  ,  -136.5, -43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -173, -92.5  ,  -157, -92.5  ,  -132.5, -71  ,  -179, -84.5  ,  -178.5, -88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -132.5, -71  ,  -130, -78.5  ,  -130.5, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -164.5, -50  ,  -162.5, -44  ,  -164, -44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134, -58.5  ,  -132.5, -67  ,  -128.5, -63  ,  -128.5, -58  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -58.5  ,  -28.5, -65  ,  -25, -64.5  ,  -23, -62.5  ,  -22.5, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, -47  ,  -28.5, -39  ,  -36, -32.5  ,  -42, -34.5  ,  -42.5, -38  ,  -37, -46.5  ,  -34.5, -50  ,  -31, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -61, -44.5  ,  -50, -40.5  ,  -54.5, -35  ,  -60, -34.5  ,  -64, -38.5  ,  -64.5, -42  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80, -60.5  ,  -80.5, -84  ,  -62, -58.5  ,  -66, -54.5  ,  -74, -54.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -57, -50.5  ,  -42.5, -38  ,  -61, -44.5  ,  -60.5, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38, -58.5  ,  -58.5, -58  ,  -62, -58.5  ,  -80.5, -84  ,  -34, -60.5  ,  -34.5, -59  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42, -34.5  ,  -36, -32.5  ,  -40, -32.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -31, -86.5  ,  -30.5, -83  ,  -30.5, -77  ,  -32.5, -71  ,  -57, -92.5  ,  -55, -94.5  ,  -39, -94.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, -79  ,  -30.5, -77  ,  -30.5, -83  ,  -28.5, -81  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, -71  ,  -30.5, -77  ,  -30.5, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30.5, -67  ,  -79, -84.5  ,  -32.5, -69  ,  -30.5, -68  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -73, -92.5  ,  -57, -92.5  ,  -32.5, -71  ,  -32.5, -69  ,  -79, -84.5  ,  -78.5, -88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, -40.5  ,  -42.5, -38  ,  -48, -38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, -58.5  ,  -28.5, -60  ,  -30.5, -67  ,  -28.5, -65  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -58.5, -58  ,  -38, -58.5  ,  -38.5, -47  ,  -42.5, -38  ,  -57, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -42.5, -38  ,  -38.5, -47  ,  -37, -46.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80.5, -84  ,  -79, -84.5  ,  -30.5, -67  ,  -28.5, -60  ,  -34, -60.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   62, -36.5  ,  61.5, -43  ,  65, -40.5  ,  65.5, -37  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   72, -56.5  ,  71.5, -58  ,  71.5, -63  ,  75, -62.5  ,  77, -60.5  ,  77.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   46, -32.5  ,  38, -32.5  ,  47.5, -41  ,  49, -40.5  ,  49.5, -35  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51.5, -38  ,  51.5, -44  ,  61.5, -51  ,  62, -46.5  ,  60, -34.5  ,  54, -34.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   62, -46.5  ,  61.5, -51  ,  63, -50.5  ,  63.5, -47  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   31.5, -52  ,  19.5, -84  ,  37.5, -48  ,  34, -48.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   62, -56.5  ,  19.5, -84  ,  67.5, -71  ,  67.5, -67  ,  66, -58.5  ,  65.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, -48  ,  50, -44.5  ,  39.5, -44  ,  38, -44.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   39.5, -44  ,  50, -44.5  ,  47.5, -41  ,  38, -32.5  ,  35.5, -36  ,  35.5, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, -58.5  ,  19.5, -84  ,  31.5, -52  ,  26, -52.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, -34.5  ,  61.5, -43  ,  62, -36.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51.5, -44  ,  50, -44.5  ,  19.5, -84  ,  62, -56.5  ,  61.5, -51  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27, -92.5  ,  43, -92.5  ,  21, -84.5  ,  21.5, -88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   69, -86.5  ,  71.5, -79  ,  70, -78.5  ,  19.5, -84  ,  21, -84.5  ,  55, -94.5  ,  61, -94.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, -71  ,  19.5, -84  ,  70, -78.5  ,  69.5, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -94.5  ,  43, -92.5  ,  45, -94.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   19.5, -84  ,  50, -44.5  ,  37.5, -48  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   66, -58.5  ,  67.5, -67  ,  71.5, -63  ,  71.5, -58  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55, -94.5  ,  21, -84.5  ,  43, -92.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   167.5, -47  ,  150, -44.5  ,  163.5, -51  ,  167, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   176, -56.5  ,  166, -58.5  ,  171.5, -63  ,  175, -62.5  ,  177.5, -59  ,  177.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   135, -42.5  ,  149.5, -41  ,  141.5, -33  ,  136, -32.5  ,  132, -36.5  ,  131.5, -40  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   171.5, -33  ,  166, -32.5  ,  164, -34.5  ,  163.5, -38  ,  169, -46.5  ,  173, -50.5  ,  177, -48.5  ,  177.5, -39  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   120, -58.5  ,  119.5, -84  ,  138, -56.5  ,  134, -52.5  ,  126, -52.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   150, -44.5  ,  167.5, -47  ,  169, -46.5  ,  163.5, -38  ,  156, -38.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   162, -56.5  ,  143, -92.5  ,  145, -94.5  ,  167.5, -71  ,  167.5, -67  ,  166, -58.5  ,  165.5, -57  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   177, -48.5  ,  173, -50.5  ,  175, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   169, -86.5  ,  169.5, -83  ,  169.5, -77  ,  167.5, -71  ,  145, -94.5  ,  161, -94.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   171.5, -79  ,  169.5, -77  ,  169.5, -83  ,  171.5, -81  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   167.5, -71  ,  169.5, -77  ,  169.5, -73  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   163.5, -51  ,  150, -44.5  ,  141.5, -56  ,  161.5, -53  ,  163.5, -52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   166, -58.5  ,  167.5, -67  ,  171.5, -63  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   141, -50.5  ,  150, -44.5  ,  149.5, -41  ,  135, -42.5  ,  135.5, -46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   141.5, -56  ,  150, -44.5  ,  141, -50.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   127, -92.5  ,  143, -92.5  ,  162, -56.5  ,  161.5, -53  ,  141.5, -56  ,  121, -84.5  ,  121.5, -88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   119.5, -84  ,  121, -84.5  ,  141.5, -56  ,  138, -56.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -128, 11.5  ,  -130, 9.5  ,  -128.5, 5  ,  -125, 5.5  ,  -123, 7.5  ,  -122.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -138, 9.5  ,  -180.5, -16  ,  -134.5, -1  ,  -128.5, 5  ,  -130, 9.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -130.5, 25  ,  -130.5, 27  ,  -132.5, 29  ,  -146, 29.5  ,  -136.5, 21  ,  -133, 21.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -131, -20.5  ,  -128.5, -13  ,  -159, -24.5  ,  -155, -28.5  ,  -139, -28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, 19  ,  -136.5, 21  ,  -146, 29.5  ,  -148, 27.5  ,  -148.5, 22  ,  -138.5, 11  ,  -134.5, 15  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -180.5, 8  ,  -180.5, -16  ,  -166, 13.5  ,  -168, 15.5  ,  -174, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, -1  ,  -132, -6.5  ,  -132.5, -3  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -165, 23.5  ,  -154.5, 31  ,  -164, 31.5  ,  -166, 29.5  ,  -166.5, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -164.5, 18  ,  -162.5, 16  ,  -152, 23.5  ,  -152.5, 29  ,  -154.5, 31  ,  -165, 23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -174.5, -24  ,  -172, -24.5  ,  -159, -24.5  ,  -128.5, -13  ,  -130, -12.5  ,  -179, -16.5  ,  -178.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -132, -6.5  ,  -130, -12.5  ,  -130.5, -7  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -162.5, 16  ,  -150, 21.5  ,  -152, 23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -150, 21.5  ,  -162.5, 16  ,  -166, 13.5  ,  -180.5, -16  ,  -138, 9.5  ,  -138.5, 11  ,  -148.5, 22  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, -1  ,  -180.5, -16  ,  -179, -16.5  ,  -130, -12.5  ,  -132, -6.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28, 11.5  ,  -28.5, 10  ,  -28.5, 5  ,  -25, 5.5  ,  -23, 7.5  ,  -22.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, 28  ,  -33, 15.5  ,  -31, 13.5  ,  -28, 29.5  ,  -30, 31.5  ,  -36, 31.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -68, 31.5  ,  -70, 29.5  ,  -62.5, 16  ,  -54, 25.5  ,  -60, 31.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -46.5, 24  ,  -33, 15.5  ,  -38.5, 28  ,  -44, 27.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -24.5, 29  ,  -28, 29.5  ,  -31, 13.5  ,  -25, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38, 11.5  ,  -62, -24.5  ,  -32.5, -3  ,  -32.5, 1  ,  -34, 9.5  ,  -34.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 25.5  ,  -62.5, 16  ,  -80.5, -16  ,  -50, 23.5  ,  -50.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -31, -18.5  ,  -28.5, -11  ,  -57, -24.5  ,  -55, -26.5  ,  -39, -26.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80, 9.5  ,  -80.5, -16  ,  -62.5, 16  ,  -74, 15.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62.5, 16  ,  -70, 29.5  ,  -70.5, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -74.5, -24  ,  -63, -24.5  ,  -62, -24.5  ,  -38, 11.5  ,  -38.5, 13  ,  -79, -16.5  ,  -78.5, -20  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -32.5, -3  ,  -62, -24.5  ,  -30, -10.5  ,  -30.5, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -34, 9.5  ,  -32.5, 1  ,  -28.5, 5  ,  -28.5, 10  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -50, 23.5  ,  -35, 15.5  ,  -33, 15.5  ,  -46.5, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -28.5, -11  ,  -30, -10.5  ,  -62, -24.5  ,  -57, -24.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -80.5, -16  ,  -35, 15.5  ,  -50, 23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -38.5, 13  ,  -80.5, -16  ,  -79, -16.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   68, -4.5  ,  67.5, -7  ,  69.5, -5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   75.5, 13  ,  71.5, 5  ,  75, 5.5  ,  77, 7.5  ,  77.5, 11  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, 24  ,  71.5, 5  ,  75.5, 13  ,  72, 25.5  ,  70, 27.5  ,  64, 27.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32, 31.5  ,  30, 29.5  ,  37, 17.5  ,  46, 25.5  ,  41.5, 31  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 17.5  ,  30, 29.5  ,  29.5, 24  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   69, -20.5  ,  71.5, -13  ,  43, -26.5  ,  45, -28.5  ,  61, -28.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   20, 7.5  ,  19.5, -18  ,  37.5, 14  ,  26, 13.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   34, -26.5  ,  43, -26.5  ,  71.5, -13  ,  70, -12.5  ,  21, -18.5  ,  21.5, -22  ,  25.5, -26  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, -7  ,  21, -18.5  ,  70, -12.5  ,  69.5, -9  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   72, 25.5  ,  75.5, 13  ,  75.5, 25  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   54, 21.5  ,  67.5, 1  ,  71.5, 5  ,  61.5, 24  ,  56, 23.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 17.5  ,  37.5, 14  ,  53.5, 23  ,  46, 25.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   19.5, -18  ,  21, -18.5  ,  54, 21.5  ,  53.5, 23  ,  37.5, 14  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, 1  ,  54, 21.5  ,  21, -18.5  ,  67.5, -7  ,  68, -4.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -159, 69.5  ,  -148, 83.5  ,  -160.5, 74  ,  -162.5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -161, 77.5  ,  -148, 83.5  ,  -148.5, 85  ,  -152, 85.5  ,  -162.5, 84  ,  -164, 83.5  ,  -164.5, 80  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -163, 85.5  ,  -152, 85.5  ,  -152.5, 93  ,  -154.5, 95  ,  -164, 95.5  ,  -166, 93.5  ,  -166.5, 88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -128.5, 39  ,  -133, 39.5  ,  -132.5, 38  ,  -129, 37.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -171, 53.5  ,  -160, 63.5  ,  -164, 65.5  ,  -172, 57.5  ,  -172.5, 54  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -102.5, 55  ,  -146.5, 84  ,  -148, 83.5  ,  -133, 39.5  ,  -128.5, 39  ,  -121, 41.5  ,  -106.5, 49  ,  -103, 51.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -146.5, 84  ,  -130, 91.5  ,  -132, 93.5  ,  -142.5, 90  ,  -146, 87.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -110, 91.5  ,  -100.5, 57  ,  -100.5, 87  ,  -104.5, 91  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -164, 65.5  ,  -160, 63.5  ,  -160.5, 65  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -142.5, 90  ,  -132, 93.5  ,  -142, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -106.5, 49  ,  -114.5, 43  ,  -109, 43.5  ,  -107, 45.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -134.5, 39  ,  -148, 83.5  ,  -156.5, 35  ,  -156.5, 34  ,  -139, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -165, 45.5  ,  -160, 63.5  ,  -171, 53.5  ,  -170.5, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -121, 41.5  ,  -128.5, 39  ,  -123, 39.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -114.5, 43  ,  -121, 41.5  ,  -115, 41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -156.5, 35  ,  -158.5, 64  ,  -160, 63.5  ,  -165, 45.5  ,  -164.5, 42  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -106.5, 49  ,  -121, 41.5  ,  -114.5, 43  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -122, 93.5  ,  -124, 91.5  ,  -100.5, 57  ,  -110, 91.5  ,  -112, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -162.5, 84  ,  -152, 85.5  ,  -163, 85.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -160.5, 74  ,  -148, 83.5  ,  -161, 77.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -158.5, 64  ,  -148, 83.5  ,  -159, 69.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -146.5, 84  ,  -102.5, 55  ,  -100.5, 57  ,  -124, 91.5  ,  -130, 91.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -156.5, 35  ,  -148, 83.5  ,  -158.5, 64  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -133, 39.5  ,  -148, 83.5  ,  -134.5, 39  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16.5, 43  ,  -16.5, 44  ,  -18.5, 42  ,  -17, 41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -63, 71.5  ,  -50, 83.5  ,  -62.5, 74  ,  -64.5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -21, 45.5  ,  -19, 45.5  ,  -17, 47.5  ,  -22.5, 49  ,  -22.5, 46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44.5, 90  ,  -38, 93.5  ,  -44, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -64.5, 84  ,  -54, 85.5  ,  -54.5, 93  ,  -56.5, 95  ,  -66, 95.5  ,  -68, 93.5  ,  -68.5, 88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -71, 53.5  ,  -62.5, 66  ,  -72, 57.5  ,  -72.5, 54  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -48.5, 84  ,  -28.5, 55  ,  -12.5, 75  ,  -14, 79.5  ,  -16, 83.5  ,  -38, 93.5  ,  -44.5, 90  ,  -48, 87.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62.5, 76  ,  -50, 83.5  ,  -50.5, 85  ,  -54, 85.5  ,  -64.5, 84  ,  -66, 83.5  ,  -66.5, 80  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -26, 95.5  ,  -36, 95.5  ,  -38, 93.5  ,  -16, 83.5  ,  -18.5, 91  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22.5, 49  ,  -17, 47.5  ,  -12.5, 75  ,  -27, 55.5  ,  -26.5, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16, 83.5  ,  -14, 79.5  ,  -14.5, 83  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -14, 79.5  ,  -12.5, 75  ,  -12.5, 79  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -31, 41.5  ,  -30.5, 45  ,  -30.5, 53  ,  -62.5, 66  ,  -65, 45.5  ,  -64.5, 42  ,  -56.5, 34  ,  -39, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30.5, 53  ,  -30.5, 45  ,  -29, 45.5  ,  -28.5, 51  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8.5, 49  ,  -10.5, 73  ,  -12.5, 75  ,  -16.5, 44  ,  -16.5, 43  ,  -11, 43.5  ,  -9, 45.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -10, 67.5  ,  -8.5, 49  ,  -4.5, 53  ,  -4.5, 65  ,  -6.5, 67  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -65, 45.5  ,  -62.5, 66  ,  -71, 53.5  ,  -70.5, 50  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -62.5, 74  ,  -50, 83.5  ,  -62.5, 76  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30.5, 53  ,  -28.5, 55  ,  -48.5, 84  ,  -50, 83.5  ,  -63, 71.5  ,  -62.5, 66  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -27, 55.5  ,  -12.5, 75  ,  -28.5, 55  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -16.5, 44  ,  -12.5, 75  ,  -17, 47.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37, 71.5  ,  37.5, 74  ,  35.5, 72  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 47.5  ,  29.5, 52  ,  28, 51.5  ,  27.5, 48  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   55.5, 90  ,  62, 93.5  ,  56, 93.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   35.5, 84  ,  46, 85.5  ,  45.5, 93  ,  43.5, 95  ,  34, 95.5  ,  32, 93.5  ,  31.5, 88  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51.5, 84  ,  73, 55.5  ,  86, 79.5  ,  82, 87.5  ,  62, 93.5  ,  55.5, 90  ,  52, 87.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   69, 41.5  ,  69.5, 45  ,  69.5, 53  ,  51.5, 84  ,  50, 83.5  ,  46, 33.5  ,  61, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 76  ,  50, 83.5  ,  49.5, 85  ,  46, 85.5  ,  35.5, 84  ,  34, 83.5  ,  33.5, 80  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   81, 45.5  ,  81.5, 59  ,  79, 49.5  ,  79.5, 46  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   84, 83.5  ,  86, 79.5  ,  85.5, 83  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   82, 87.5  ,  84, 83.5  ,  83.5, 87  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   29.5, 58  ,  29.5, 52  ,  33, 47.5  ,  31.5, 62  ,  30, 61.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   27.5, 54  ,  29.5, 52  ,  29.5, 58  ,  27.5, 56  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   69.5, 53  ,  69.5, 45  ,  71, 45.5  ,  71.5, 51  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   75.5, 50  ,  79, 49.5  ,  81.5, 59  ,  79.5, 61  ,  73, 55.5  ,  73.5, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   79.5, 93  ,  76, 93.5  ,  82, 87.5  ,  81.5, 91  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   32, 65.5  ,  31.5, 62  ,  33, 47.5  ,  37.5, 68  ,  34, 67.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   87, 65.5  ,  87.5, 79  ,  79.5, 61  ,  83, 61.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   64, 95.5  ,  62, 93.5  ,  82, 87.5  ,  74, 95.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   43.5, 34  ,  46, 33.5  ,  50, 83.5  ,  35, 45.5  ,  35.5, 42  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 68  ,  50, 83.5  ,  37.5, 74  ,  37, 71.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   87.5, 79  ,  86, 79.5  ,  73, 55.5  ,  79.5, 61  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   37.5, 74  ,  50, 83.5  ,  37.5, 76  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 47.5  ,  35, 45.5  ,  50, 83.5  ,  37.5, 68  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51.5, 84  ,  71.5, 55  ,  73, 55.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 1, friction = 0.69999999999999996, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   51.5, 84  ,  69.5, 53  ,  71.5, 55  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

