-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["map01"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   575, 97.5  ,  639.5, 287  ,  511, 161.5  ,  511.5, 98  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, 161.5  ,  191.5, 223  ,  -65, 223.5  ,  -64.5, 162  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   511, 161.5  ,  639.5, 287  ,  447, 223.5  ,  447.5, 162  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, 223  ,  -1, 161.5  ,  -0.5, 98  ,  1, 97.5  ,  191, 97.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   639, 33.5  ,  639.5, 35  ,  639.5, 287  ,  575, 97.5  ,  575.5, 34  ,  577, 33.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -319, 223.5  ,  -65, 223.5  ,  -320.5, 286  ,  -320.5, 224  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   191.5, 223  ,  193, 223.5  ,  -320, 287.5  ,  -320.5, 286  ,  -65, 223.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   639.5, 287  ,  638, 287.5  ,  -320, 287.5  ,  193, 223.5  ,  447, 223.5  }
                    }
                    
                    
                    
                     ,
                    
                    
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -384.5, 287  ,  -640, 287.5  ,  -454, 223.5  ,  -385, 223.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "", density = 10, friction = 2.0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -454, 223.5  ,  -640, 287.5  ,  -640.5, 224  }
                    }
                    
                    
                    
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

